name: Test Scraper Manager

on:
  workflow_dispatch:

jobs:
  test-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper Manager
        run: python E0_ScraperManager.py

      - name: Show E1 output
        run: cat E1_NewsAfterScrapingRun.json
